//==========================================================================================================================
//Key is used to ensure the consistency of file version and content, and cannot be modified.
//Version Control is the version number written when the file is generated and cannot be modified.
//ToolMessage is used to record related information of any tool that has processed the file and cannot be manually modified.
//UserMessage is used by the user to write any information, which can be modified in any way.
//Content is the actual payload of the file.
//Parameter is the additional parameter information carried by the file and cannot be modified in any way.

//Key is generated by the hash of Version Control, Content and Parameter to ensure the consistency of the file.
//These three parts do not allow any individual modification
//==========================================================================================================================


//[UHDL]Key Start [md5:04f9f2d1ac6fded7d5285df179aac31d]
//Version Control Hash: 3accddf64b1dd03abeb9b0b3e5a7ba44
//Content Hash: ad4250ae6ca6e849fada4cec772fb42c
//Parameter Hash: d41d8cd98f00b204e9800998ecf8427e
//[UHDL]Key End [md5:04f9f2d1ac6fded7d5285df179aac31d]

//[UHDL]Version Control Start [md5:3accddf64b1dd03abeb9b0b3e5a7ba44]
//[UHDL]Version Control Version:1.0.1
//[UHDL]Version Control End [md5:3accddf64b1dd03abeb9b0b3e5a7ba44]

//[UHDL]Tool Message Start [md5:26ca37b2769297a9562fd5c2344b54ed]
//Written by UHDL in 2023-07-17 11:17:27
//[UHDL]Tool Message End [md5:26ca37b2769297a9562fd5c2344b54ed]

//[UHDL]User Message Start [md5:d41d8cd98f00b204e9800998ecf8427e]

//[UHDL]User Message End [md5:d41d8cd98f00b204e9800998ecf8427e]

//[UHDL]Content Start [md5:ad4250ae6ca6e849fada4cec772fb42c]
RegSpaceAPB_cfg_reg_bank_A/RegSpaceBase_cfg_reg_bank_A.v
RegSpaceAPB_cfg_reg_bank_A/RegSpaceAPB_cfg_reg_bank_A.v
//[UHDL]Content End [md5:ad4250ae6ca6e849fada4cec772fb42c]

//[UHDL]Parameter Start [md5:d41d8cd98f00b204e9800998ecf8427e]

//[UHDL]Parameter End [md5:d41d8cd98f00b204e9800998ecf8427e]

