//==========================================================================================================================
//Key is used to ensure the consistency of file version and content, and cannot be modified.
//Version Control is the version number written when the file is generated and cannot be modified.
//ToolMessage is used to record related information of any tool that has processed the file and cannot be manually modified.
//UserMessage is used by the user to write any information, which can be modified in any way.
//Content is the actual payload of the file.
//Parameter is the additional parameter information carried by the file and cannot be modified in any way.

//Key is generated by the hash of Version Control, Content and Parameter to ensure the consistency of the file.
//These three parts do not allow any individual modification
//==========================================================================================================================


//[UHDL]Key Start [md5:40c922af89f5dd8ff9383d3a59c04f9b]
//Version Control Hash: 3accddf64b1dd03abeb9b0b3e5a7ba44
//Content Hash: e812557c43ffd9e0a1a6d03eb3c3c079
//Parameter Hash: d41d8cd98f00b204e9800998ecf8427e
//[UHDL]Key End [md5:40c922af89f5dd8ff9383d3a59c04f9b]

//[UHDL]Version Control Start [md5:3accddf64b1dd03abeb9b0b3e5a7ba44]
//[UHDL]Version Control Version:1.0.1
//[UHDL]Version Control End [md5:3accddf64b1dd03abeb9b0b3e5a7ba44]

//[UHDL]Tool Message Start [md5:26ca37b2769297a9562fd5c2344b54ed]
//Written by UHDL in 2023-07-17 11:17:27
//[UHDL]Tool Message End [md5:26ca37b2769297a9562fd5c2344b54ed]

//[UHDL]User Message Start [md5:d41d8cd98f00b204e9800998ecf8427e]

//[UHDL]User Message End [md5:d41d8cd98f00b204e9800998ecf8427e]

//[UHDL]Content Start [md5:e812557c43ffd9e0a1a6d03eb3c3c079]
RegSpaceAPB_cfg_external/RegSpaceBase_cfg_external.v
RegSpaceAPB_cfg_external/RegSpaceAPB_cfg_external.v
//[UHDL]Content End [md5:e812557c43ffd9e0a1a6d03eb3c3c079]

//[UHDL]Parameter Start [md5:d41d8cd98f00b204e9800998ecf8427e]

//[UHDL]Parameter End [md5:d41d8cd98f00b204e9800998ecf8427e]

