//==========================================================================================================================
//Key is used to ensure the consistency of file version and content, and cannot be modified.
//Version Control is the version number written when the file is generated and cannot be modified.
//ToolMessage is used to record related information of any tool that has processed the file and cannot be manually modified.
//UserMessage is used by the user to write any information, which can be modified in any way.
//Content is the actual payload of the file.
//Parameter is the additional parameter information carried by the file and cannot be modified in any way.

//Key is generated by the hash of Version Control, Content and Parameter to ensure the consistency of the file.
//These three parts do not allow any individual modification
//==========================================================================================================================


//[UHDL]Key Start [md5:61bb73125178f09f76924aa36f2bb134]
//Version Control Hash: 3accddf64b1dd03abeb9b0b3e5a7ba44
//Content Hash: b704b9981095d44a44eb46c0dc023064
//Parameter Hash: d41d8cd98f00b204e9800998ecf8427e
//[UHDL]Key End [md5:61bb73125178f09f76924aa36f2bb134]

//[UHDL]Version Control Start [md5:3accddf64b1dd03abeb9b0b3e5a7ba44]
//[UHDL]Version Control Version:1.0.1
//[UHDL]Version Control End [md5:3accddf64b1dd03abeb9b0b3e5a7ba44]

//[UHDL]Tool Message Start [md5:136c2ca90c4703b692ea0470be1feb9c]
//Written by UHDL in 2023-07-10 10:19:50
//[UHDL]Tool Message End [md5:136c2ca90c4703b692ea0470be1feb9c]

//[UHDL]User Message Start [md5:d41d8cd98f00b204e9800998ecf8427e]

//[UHDL]User Message End [md5:d41d8cd98f00b204e9800998ecf8427e]

//[UHDL]Content Start [md5:b704b9981095d44a44eb46c0dc023064]
module RegSpaceRTL_cfg_reg_bank_D (
	input             clk                ,
	input             rst_n              ,
	input      [31:0] rreq_addr          ,
	input             rreq_vld           ,
	output            rreq_rdy           ,
	output reg [31:0] rack_data          ,
	output reg        rack_vld           ,
	input             rack_rdy           ,
	input      [31:0] wreq_addr          ,
	input      [31:0] wreq_data          ,
	input             wreq_vld           ,
	output reg        wreq_rdy           ,
	input             reg0_field1_wdat   ,
	input             reg0_field1_wenable,
	output            reg0_field1_rdat   ,
	input      [1:0]  reg0_field2_wdat   ,
	input             reg0_field2_wenable,
	output     [1:0]  reg0_field2_rdat   ,
	input      [2:0]  reg0_field3_wdat   ,
	input             reg0_field3_wenable,
	output     [2:0]  reg0_field3_rdat   ,
	input      [3:0]  reg0_field4_wdat   ,
	input             reg0_field4_wenable,
	output     [3:0]  reg0_field4_rdat   ,
	input             reg1_field1_wdat   ,
	input             reg1_field1_wenable,
	output            reg1_field1_rdat   ,
	input      [1:0]  reg1_field2_wdat   ,
	input             reg1_field2_wenable,
	output     [1:0]  reg1_field2_rdat   ,
	input      [2:0]  reg1_field3_wdat   ,
	input             reg1_field3_wenable,
	output     [2:0]  reg1_field3_rdat   ,
	input      [3:0]  reg1_field4_wdat   ,
	input             reg1_field4_wenable,
	output     [3:0]  reg1_field4_rdat   );
	wire [31:0] reg0_rdat  ;
	wire [0:0]  reg0_rrdy  ;
	wire [31:0] reg0_wdat  ;
	wire [0:0]  reg0_wvld  ;
	reg  [0:0]  reg0_field1;
	reg  [1:0]  reg0_field2;
	reg  [2:0]  reg0_field3;
	reg  [3:0]  reg0_field4;
	wire [31:0] reg1_rdat  ;
	wire [0:0]  reg1_rrdy  ;
	wire [31:0] reg1_wdat  ;
	wire [0:0]  reg1_wvld  ;
	reg  [0:0]  reg1_field1;
	reg  [1:0]  reg1_field2;
	reg  [2:0]  reg1_field3;
	reg  [3:0]  reg1_field4;
	assign rreq_rdy = (rack_rdy && rack_vld);
	
	always @(*) begin
	    if((rreq_addr == 32'b0)) rack_data = reg0_rdat;
	    else if((rreq_addr == 32'b100000)) rack_data = reg1_rdat;
	    else rack_data = 32'b0;
	end
	
	always @(*) begin
	    if((rreq_addr == 32'b0)) rack_vld = 1'b1;
	    else if((rreq_addr == 32'b100000)) rack_vld = 1'b1;
	    else rack_vld = 1'b0;
	end
	
	always @(*) begin
	    if((wreq_addr == 32'b0)) wreq_rdy = 1'b1;
	    else if((wreq_addr == 32'b100000)) wreq_rdy = 1'b1;
	    else wreq_rdy = 1'b0;
	end
	
	assign reg0_rdat = {2'b0, reg0_field1, reg0_field2, reg0_field3, 1'b0, reg0_field4, 19'b0};
	
	assign reg0_rrdy = (rreq_vld && (rreq_addr == 32'b0));
	
	assign reg0_wdat = wreq_data;
	
	assign reg0_wvld = (wreq_vld && (wreq_addr == 32'b0));
	
	always @(posedge clk or negedge rst_n) begin
	    if(~rst_n) reg0_field1 <= 1'b0;
	    else begin
	        if(reg0_field1_wenable) reg0_field1 <= reg0_field1_wdat;
	        else if(reg0_wvld) reg0_field1 <= reg0_wdat[2:2];
	        else if(reg0_rrdy) reg0_field1 <= 1'b0;
	    end
	end
	
	assign reg0_field1_rdat = reg0_field1;
	
	always @(posedge clk or negedge rst_n) begin
	    if(~rst_n) reg0_field2 <= 2'b0;
	    else begin
	        if(reg0_field2_wenable) reg0_field2 <= reg0_field2_wdat;
	        else if(reg0_wvld) reg0_field2 <= reg0_wdat[4:3];
	        else if(reg0_rrdy) reg0_field2 <= 2'b0;
	    end
	end
	
	assign reg0_field2_rdat = reg0_field2;
	
	always @(posedge clk or negedge rst_n) begin
	    if(~rst_n) reg0_field3 <= 3'b0;
	    else begin
	        if(reg0_field3_wenable) reg0_field3 <= reg0_field3_wdat;
	        else if(reg0_wvld) reg0_field3 <= reg0_wdat[7:5];
	        else if(reg0_rrdy) reg0_field3 <= 3'b0;
	    end
	end
	
	assign reg0_field3_rdat = reg0_field3;
	
	always @(posedge clk or negedge rst_n) begin
	    if(~rst_n) reg0_field4 <= 4'b0;
	    else begin
	        if(reg0_field4_wenable) reg0_field4 <= reg0_field4_wdat;
	        else if(reg0_wvld) reg0_field4 <= reg0_wdat[12:9];
	        else if(reg0_rrdy) reg0_field4 <= 4'b0;
	    end
	end
	
	assign reg0_field4_rdat = reg0_field4;
	
	assign reg1_rdat = {2'b0, reg1_field1, reg1_field2, reg1_field3, 1'b0, reg1_field4, 19'b0};
	
	assign reg1_rrdy = (rreq_vld && (rreq_addr == 32'b100000));
	
	assign reg1_wdat = wreq_data;
	
	assign reg1_wvld = (wreq_vld && (wreq_addr == 32'b100000));
	
	always @(posedge clk or negedge rst_n) begin
	    if(~rst_n) reg1_field1 <= 1'b0;
	    else begin
	        if(reg1_field1_wenable) reg1_field1 <= reg1_field1_wdat;
	        else if(reg1_wvld) reg1_field1 <= reg1_wdat[2:2];
	        else if(reg1_rrdy) reg1_field1 <= 1'b0;
	    end
	end
	
	assign reg1_field1_rdat = reg1_field1;
	
	always @(posedge clk or negedge rst_n) begin
	    if(~rst_n) reg1_field2 <= 2'b0;
	    else begin
	        if(reg1_field2_wenable) reg1_field2 <= reg1_field2_wdat;
	        else if(reg1_wvld) reg1_field2 <= reg1_wdat[4:3];
	        else if(reg1_rrdy) reg1_field2 <= 2'b0;
	    end
	end
	
	assign reg1_field2_rdat = reg1_field2;
	
	always @(posedge clk or negedge rst_n) begin
	    if(~rst_n) reg1_field3 <= 3'b0;
	    else begin
	        if(reg1_field3_wenable) reg1_field3 <= reg1_field3_wdat;
	        else if(reg1_wvld) reg1_field3 <= reg1_wdat[7:5];
	        else if(reg1_rrdy) reg1_field3 <= 3'b0;
	    end
	end
	
	assign reg1_field3_rdat = reg1_field3;
	
	always @(posedge clk or negedge rst_n) begin
	    if(~rst_n) reg1_field4 <= 4'b0;
	    else begin
	        if(reg1_field4_wenable) reg1_field4 <= reg1_field4_wdat;
	        else if(reg1_wvld) reg1_field4 <= reg1_wdat[12:9];
	        else if(reg1_rrdy) reg1_field4 <= 4'b0;
	    end
	end
	
	assign reg1_field4_rdat = reg1_field4;
	

endmodule
//[UHDL]Content End [md5:b704b9981095d44a44eb46c0dc023064]

//[UHDL]Parameter Start [md5:d41d8cd98f00b204e9800998ecf8427e]

//[UHDL]Parameter End [md5:d41d8cd98f00b204e9800998ecf8427e]

