//==========================================================================================================================
//Key is used to ensure the consistency of file version and content, and cannot be modified.
//Version Control is the version number written when the file is generated and cannot be modified.
//ToolMessage is used to record related information of any tool that has processed the file and cannot be manually modified.
//UserMessage is used by the user to write any information, which can be modified in any way.
//Content is the actual payload of the file.
//Parameter is the additional parameter information carried by the file and cannot be modified in any way.

//Key is generated by the hash of Version Control, Content and Parameter to ensure the consistency of the file.
//These three parts do not allow any individual modification
//==========================================================================================================================


//[UHDL]Key Start [md5:2265e5fafe044162fbbd208223b3a783]
//Version Control Hash: 3accddf64b1dd03abeb9b0b3e5a7ba44
//Content Hash: 6b45e40aac1cce8221cad867cb53f57e
//Parameter Hash: d41d8cd98f00b204e9800998ecf8427e
//[UHDL]Key End [md5:2265e5fafe044162fbbd208223b3a783]

//[UHDL]Version Control Start [md5:3accddf64b1dd03abeb9b0b3e5a7ba44]
//[UHDL]Version Control Version:1.0.1
//[UHDL]Version Control End [md5:3accddf64b1dd03abeb9b0b3e5a7ba44]

//[UHDL]Tool Message Start [md5:1cb60800d9deb8242456d9b4ed777943]
//Written by UHDL in 2023-07-17 11:17:28
//[UHDL]Tool Message End [md5:1cb60800d9deb8242456d9b4ed777943]

//[UHDL]User Message Start [md5:d41d8cd98f00b204e9800998ecf8427e]

//[UHDL]User Message End [md5:d41d8cd98f00b204e9800998ecf8427e]

//[UHDL]Content Start [md5:6b45e40aac1cce8221cad867cb53f57e]
RegSpaceAPB_cfg_sw_read_clean/RegSpaceBase_cfg_sw_read_clean.v
RegSpaceAPB_cfg_sw_read_clean/RegSpaceAPB_cfg_sw_read_clean.v
//[UHDL]Content End [md5:6b45e40aac1cce8221cad867cb53f57e]

//[UHDL]Parameter Start [md5:d41d8cd98f00b204e9800998ecf8427e]

//[UHDL]Parameter End [md5:d41d8cd98f00b204e9800998ecf8427e]

